# Generated by Django 5.2.5 on 2025-09-06 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+234XXXXXXXXXX' (14 digits total).", regex='^\\+234\\d{10}$')]),
        ),
    ]
