# Generated by Django 5.2.5 on 2025-09-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_verification_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_verification_token',
        ),
    ]
