services:
  - type: web
    name: hostify
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn hostify.wsgi:application
    staticPublish:
      - name: static
        path: /static/
        source: staticfiles
      - name: media
        path: /media/
        source: media
