# Generated by Django 5.0.6 on 2025-01-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='logo',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='address',
            field=models.CharField(help_text='Hotel Address.', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(help_text='Enter hotel description'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(help_text='Enter the name of the hotel (e.g., Grand Plaza Hotel).', max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='upload a picture of your hotel the front view', related_name='hotels', to='core.hotelphoto'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
