# Generated by Django 5.0.6 on 2024-12-27 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_verified_alter_booking_check_in_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verified',
            new_name='verified_email',
        ),
    ]
