# Generated by Django 5.0.6 on 2025-01-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_hotelphoto_photo_remove_hotel_photos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='images',
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=models.ImageField(blank=True, help_text='Upload a photo of your hotel', upload_to='hotel_photos/'),
        ),
    ]
