# Generated by Django 5.0.6 on 2024-12-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_verified_customuser_verified_email'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Contact phone number for the establishment.', max_length=15, null=True),
        ),
    ]
