STATES = (
    ("abia", "Abia"),
    ("abuja", "Abuja"),
    ("adamawa", "Adamawa"),
    ("akwaibom", "Akwa Ibom"),
    ("anambra", "Anambra"),
    ("bauchi", "Bauchi"),
    ("bayelsa", "Bayelsa"),
    ("benue", "Benue"),
    ("borno", "Borno"),
    ("crossriver", "Cross River"),
    ("delta", "Delta"),
    ("ebonyi", "Ebonyi"),
    ("edo", "Edo"),
    ("ekiti", "Ekiti"),
    ("enugu", "Enugu"),
    ("gombe", "Gombe"),
    ("imo", "Imo"),
    ("jigawa", "Jigawa"),
    ("kaduna", "Kaduna"),
    ("kano", "Kano"),
    ("katsina", "Katsina"),
    ("kebbi", "Kebbi"),
    ("kogi", "Kogi"),
    ("kwara", "Kwara"),
    ("lagos", "Lagos"),
    ("nasarawa", "Nasarawa"),
    ("niger", "Niger"),
    ("ogun", "Ogun"),
    ("ondo", "Ondo"),
    ("osun", "Osun"),
    ("oyo", "Oyo"),
    ("plateau", "Plateau"),
    ("rivers", "Rivers"),
    ("sokoto", "Sokoto"),
    ("taraba", "Taraba"),
    ("yobe", "Yobe"),
    ("zamfara", "Zamfara"),
)